areas = [    
    {
        keyword: "bramble_path",
        title: "The Bramble Path",
        description: "The ancient pathways were overgrown and hard to discern which way was which.",
        narration: "",
        update: "",
        locations: [
            {
                coordinates: [2,5],
                visited: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [1,5],
                west: [2,4],
                east: null,
                south: [3,5],                
            },
            {
                coordinates: [2,4],
                visited: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [2,3],
                east: [2,5],
                south: null,                
            },
            {
                coordinates: [2,3],
                visited: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: [2,4],
                south: null,                
            },
            {
                coordinates: [1,5],
                visited: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: null,
                south: [2,5],                
            },
            {
                coordinates: [3,5],
                visited: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [2,5],
                west: null,
                east: [4,6],
                south: null,                
            },
            {
                coordinates: [3,6],
                visited: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [3,5],
                east: [3,7],
                south: null,                
            },
            {
                coordinates: [3,7],
                visited: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [3,6],
                east: null,
                south: null,                
            }
        ]
    }
]