areas = [    
    {
        title: "Gossamer Gardens",
        description: "Hints of an old garden maze in some age past could be seen in the manicured lines of stone paths. It had long been left to it's own devices; grown into a tangle of briar and thorny roses bushes.\n\nAncient brambles covered ancient secrets.",
        narration: "",
        update: "",
        locations: [
            {
                coordinate: [2,5],
                items: [],
                monsters: [],
                npcs: [],
                north: [1,5],
                west: [2,4],
                east: null,
                south: [3,5],
            },
            {
                coordinate: [2,4],
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [2,3],
                east: [2,5],
                south: null,
            },
            {
                coordinate: [2,3],
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: [2,4],
                south: null,
            },
            {
                coordinate: [1,5],
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: null,
                south: [2,5],
            },
            {
                coordinate: [3,5],
                items: [],
                monsters: [],
                npcs: [],
                north: [2,5],
                west: null,
                east: [4,6],
                south: null,
            },
            {
                coordinate: [4,6],
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [3,5],
                east: [3,7],
                south: null,
            },
            {
                coordinate: [3,7],
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [3,6],
                east: null,
                south: null,
            }
        ]
    }
]