areasRef = [    
    {
        keyword: "bramble_path",
        title: "The Bramble Path",
        description: "The ancient pathways were overgrown and hard to discern which way was which.",
        narration: "",
        update: "",
        locations: [
            {
                coordinates: [2,5],
                visited: false,
                seen: false,
                items: ["green_herb_pickup"],
                monsters: [],
                npcs: ["shrine"],
                north: [1,5],
                west: [2,4],
                east: null,
                south: [3,5],
                door: null
            },
            {
                coordinates: [2,4],
                visited: false,
                seen: false,
                items: ["crimson_gate"],
                monsters: ["goblin_01"],
                npcs: [],
                north: [1,4],
                west: [2,3],
                east: [2,5],
                south: null,
                door: null
            },
            {
                coordinates: [2,3],
                visited: false,
                seen: false,
                items: [],
                monsters: ["goblin_01"],
                npcs: [],
                north: null,
                west: [2,2],
                east: [2,4],
                south: null,
                door: null
            },
            {
                coordinates: [1,5],
                visited: false,
                seen: false,
                items: ["ore"],
                monsters: [],
                npcs: ["ryth"],
                north: null,
                west: null,
                east: null,
                south: [2,5],
                door: null
            },
            {
                coordinates: [3,5],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [2,5],
                west: null,
                east: [3,6],
                south: null,
                door: null
            },
            {
                coordinates: [3,6],
                visited: false,
                seen: false,
                items: ["thorny_bramble"],
                monsters: ["grub_01"],
                npcs: [],
                north: null,
                west: [3,5],
                east: [3,7],
                south: null,
                door: null
            },
            {
                coordinates: [3,7],
                visited: false,
                seen: false,
                items: ["crimson_key"],
                monsters: ["grub_02"],
                npcs: [],
                north: null,
                west: [3,6],
                east: null,
                south: null,
                door: null
            },
            {
                coordinates: [1,4],
                visited: false,
                seen: false,
                items: ["relic"],
                monsters: ["centipede"],
                npcs: [],
                north: null,
                west: null,
                east: null,
                south: [2,4],
                door: null
            },
            {
                coordinates: [2,2],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: [2,3],
                south: null,
                door: {area: "thorn_hollow", coordinates: [2,7]}
            }
        ]
    },
    {
        keyword: "thorn_hollow",
        title: "Thorn Hollow",
        description: "Despite the thick overgrowth, these pathways snaked their way through the old maze.",
        narration: "",
        update: "",
        locations: [
            {
                coordinates: [2,7],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [2,6],
                east: null,
                south: null,
                door: {area: "bramble_path", coordinates: [2,2]}
            },
            {
                coordinates: [2,6],
                visited: false,
                seen: false,
                items: ["green_herb_pickup"],
                monsters: [],
                npcs: [],
                north: null,
                west: [2,5],
                east: [2,7],
                south: null,
                door: null
            },
            {
                coordinates: [2,5],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [1,5],
                west: null,
                east: [2,6],
                south: [3,5],
                door: null
            },
            {
                coordinates: [2,3],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [1,3],
                west: [2,2],
                east: null,
                south: [3,3],
                door: null
            },
            {
                coordinates: [2,2],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: [2,3],
                south: null,
                door: null
            },
            {
                coordinates: [1,5],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [1,4],
                east: null,
                south: [2,5],
                door: null
            },
            {
                coordinates: [1,4],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [0,4],
                west: [1,3],
                east: [1,5],
                south: null,
                door: null
            },
            {
                coordinates: [1,3],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: [1,4],
                south: [2,3],
                door: null
            },
            {
                coordinates: [0,4],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: null,
                south: [1,4],
                door: null
            },
            {
                coordinates: [3,5],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [2,5],
                west: [3,4],
                east: null,
                south: null,
                door: null
            },
            {
                coordinates: [3,4],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: [3,3],
                east: [3,5],
                south: null,
                door: null
            },
            {
                coordinates: [3,3],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [2,3],
                west: null,
                east: [3,4],
                south: [4,3],
                door: null
            },
            {
                coordinates: [4,3],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: [3,3],
                west: [4,2],
                east: null,
                south: null,
                door: null
            },
            {
                coordinates: [4,2],
                visited: false,
                seen: false,
                items: [],
                monsters: [],
                npcs: [],
                north: null,
                west: null,
                east: [4,3],
                south: null,
                door: null
            }
        ]
    }
]