items = [
    {
        keyword: "strange_stone",
        title: "Strangely shaped stone",
        shortTitle: "stone",
        description: "Smooth as an ocean stone but undulating gently as though there's something growing within it.",        
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,        
        actions: [              
        ],
    },
    {
        keyword: "straight_sword",
        title: "Old Rhenish straight sword",
        shortTitle: "sword",
        itemType: "weapon",
        canEquip: true,
        equipped: true,
        canUpgrade: true,
        level: 0,
        power: 20,
        stamina: 0,
        defence: 0,
        upgradeMaterial: ["ore"],        
        actions: [   
            {                
                type: 7,                
                title: "Attack with piercing strike",
                func: "attack|1"
            }            
        ],
    },        
    {
        keyword: "worn_shield",
        title: "Battered wooden shield.",
        shortTitle: "shield",
        itemType: "armor",
        canEquip: true,
        equipped: true,
        canUpgrade: true,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 10,
        upgradeMaterial: ["leather"],        
        actions: [
            {                
                type: 7,                
                title: "Block with you shield",
                func: "block|3"
            } 
        ],
    },
    {
        keyword: "green_cloak",
        title: "Long green cloak of the Woodland Protectors",
        shortTitle: "cloak",
        itemType: "armor",
        canEquip: true,
        equipped: true,
        canUpgrade: true,
        level: 0,
        power: 0,
        stamina: 1,
        defence: 0,
        upgradeMaterial: ["leather"],        
        actions: [               
        ],
    },
    {
        keyword: "curse_mark",
        title: "Scarred curse mark",
        shortTitle: "mark",
        canEquip: false,
        equipped: true,
        canUpgrade: false,
        level: 0,
        power: 5,
        stamina: 0,
        defence: 0,        
        actions: [               
        ],
    },
    {
        keyword: "silver_locket",
        title: "Simple silver locket",
        shortTitle: "locket",
        canEquip: true,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 10,
        defence: 0,        
        actions: [               
        ],
    },
    {
        keyword: "key",
        title: "Simple brass key",
        shortTitle: "key",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,        
        actions: [               
        ],
    },
    {
        keyword: "ripe_fruit",
        title: "Perfectly ripe piece of fruit",
        shortTitle: "fruit",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,        
        actions: [              
        ],
    },        
    {
        keyword: "iron_longsword",
        title: "Iron Longsword",
        shortTitle: "longsword",
        description: "A relic of the time before the burning war when there was still forests in Rhen that needed protecting. A simple blade made for those who moved silently through the woodlands.",
        canEquip: true,
        equipped: true,
        canUpgrade: true,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 10,
        cost: 1,        
        actions: [                
        ],
    },        
    {
        keyword: "eagle_shield",
        title: "Eagle Shield",
        shortTitle: "shield",
        canEquip: true,
        equipped: true,
        canUpgrade: true,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 10,
        cost: 250,
        actions: [                
        ],
    },        
    {
        keyword: "deepstone_talisman",
        title: "Deepstone Talisman",
        shortTitle: "shield",
        canEquip: true,
        equipped: true,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 5,
        defence: 0,
        cost: 560,        
        actions: [                
        ],
    },        
    {
        keyword: "ore",
        title: "Refined Ore",
        shortTitle: "ore",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,
        cost: 0,
        quantity: 0,        
        actions: [                
        ],
    },        
    {
        keyword: "leather",
        title: "Hardened Leather",
        shortTitle: "ore",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,
        cost: 0,
        quantity: 0,        
        actions: [                
        ],
    },        
    {
        keyword: "coins",
        title: "Handful of gold coins",
        shortTitle: "coins",
        itemType: "pickupGold",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,
        cost: 0,
        quantity: 20,        
        actions: [                
        ],
    },        
    {
        keyword: "relic",
        title: "Broken piece of stone, etched it lines of power",
        shortTitle: "relic",
        itemType: "pickupInsight",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,
        cost: 0,
        quantity: 1,        
        actions: [                
        ],
    },  
    {
        keyword: "corpse",
        title: "Your remains, aged and decayed down to bone",
        shortTitle: "corpse",
        itemType: "pickupCorpse",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,
        cost: 0,
        quantity: 0,        
        actions: [                
        ],
    },  
    {
        keyword: "green_herb",
        title: "Young Green Herb",
        shortTitle: "herb",
        itemType: "healGreenHerb",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,
        cost: 0,
        quantity: 0,
        actions: [                
        ],
    },  
    {
        keyword: "green_herb_pickup",
        title: "Young Green Herb",
        shortTitle: "herb",
        itemType: "pickupGreenHerb",
        canEquip: false,
        equipped: false,
        canUpgrade: false,
        level: 0,
        power: 0,
        stamina: 0,
        defence: 0,
        cost: 0,
        quantity: 1,
        actions: [                
        ],
    }
];
