
locations = [
    
    
    
    //----------------------//
    //-- The Old Monastery 
    //----------------------//
    {        
        keyword: "old_monastery_title",
        area: "old_monastery",
        title: "The Old Monastery",
        description: "At the city's edge, lay a Monastery older than most things man-made in this place. Once a flourishing place of worship, it had been left to decay and to slowly sink into the soft earth.",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "east_gate",
        area: "old_monastery",
        title: "The East Gate",        
        description: "A wide arched passage stood between two crumbling pieces of wall. It offered the Monastery little in terms of protection but the worn footpath leading outwards showed it still marked the border between the interior and the Valley beyond.",
        narration: "arrive_monastery",        
        update: "",        
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "shrouded_plaza",
        east: "gg_01",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "shrouded_plaza",
        area: "old_monastery",
        title: "The Shrouded Plaza",
        description: "A field of grass and flowers sat at the feet of an ancient looking Monastery. Tall grass and leaves overhead formed a tight canopy, giving this place a feeling of comfort and protection.",
        narration: "",        
        update: "",        
        items: [""],
        monsters: [""],
        npcs: ["camp"],
        north: "sanctum_steps",
        west: "",
        east: "east_gate",
        south: "library",
        up: "",
        down: ""        
    },
    {        
        keyword: "sanctum_steps",
        area: "old_monastery",
        title: "The Sanctum Steps",
        description: "The steps leading up toward the Monastery Sanctum meandered back and forth making the trip up to the ancient building unneccsarily long.\n\nSmooth stone appeared in patches among the clinging moss and lichen that covered it.",
        narration: "",        
        update: "",        
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "sanctum_hall",
        west: "",
        east: "",
        south: "shrouded_plaza",
        up: "",
        down: ""        
    },
    {        
        keyword: "sanctum_hall",
        area: "old_monastery",
        title: "The Sanctum Hall",
        description: "Shafts of light shone through old glass windows, illuminating a cavernous space inside the Monastery Sanctum.",
        narration: "",        
        update: "",        
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "sanctum_altar",
        west: "",
        east: "",
        south: "sanctum_steps",
        up: "",
        down: ""        
    },
    {        
        keyword: "sanctum_altar",
        area: "old_monastery",
        title: "The Sanctum Altar",
        description: "At the back of the Sanctum Hall was a low altar covered with ceramic dishes containing various offerings.\n\nDraped in shadow and standing watch over the altar was a large guardian-dog statue. It's eyes were fierce and you swore you could see a flicker of flame within them.",
        narration: "",        
        update: "",        
        items: [""],
        monsters: [""],
        npcs: ["oryan"],
        north: "",
        west: "",
        east: "",
        south: "sanctum_hall",
        up: "",
        down: ""        
    },    
    {        
        keyword: "library",
        area: "old_monastery",
        title: "The Forest Library",
        description: "Once a place of gathered knowledge, it had long since been left to the earth, the floor sunken away to grass and soil, vines crawled up the clay walls.\n\nAt the back of the chamber, a staircase spiraled it's way upwards",
        narration: "library",        
        update: "",        
        items: [""],
        monsters: [""],
        npcs: ["morgan"],
        north: "shrouded_plaza",
        west: "",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    









    


    //----------------------//
    //-- Gossamer Gardens
    //----------------------//
    {        
        keyword: "gossamer_gardens_title",
        area: "gossamer_gardens",
        title: "Gossamer Gardens",
        description: "Hints of an old garden maze in some age past could be seen in the manicured lines of stone paths. It had long been left to it's own devices; grown into a tangle of briar and thorny roses bushes.\n\nAncient brambles covered ancient secrets.",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    {                
        keyword: "edge_garden",
        area: "",
        title: "Edge of the Garden",        
        description: "At the threshold where a dark woodland gave way to shrubs and saplings. Ahead the foliage was being choked out by a briarwood stretching as far as you could see.",
        narration: "beginning",        
        update: "You awoke from a dream that felt unending. The last weeks of travel are lost in a blur and where the roads have led you is not entirely clear.",
        items: [""],
        monsters: [""],
        npcs: ["camp"],
        north: "gg_09",
        west: "",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_01",
        area: "gossamer_gardens",
        title: "gossamer gardens entrance",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "east_gate",
        east: "gg_02",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_02",
        area: "gossamer_gardens",
        title: "gg_02",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "gg_01",
        east: "gg_03",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_03",
        area: "gossamer_gardens",
        title: "gg_03",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: ["grub_04"],
        npcs: [""],
        north: "gg_04",
        west: "gg_02",
        east: "gg_06",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_04",
        area: "gossamer_gardens",
        title: "gg_04",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_05",
        west: "",
        east: "",
        south: "gg_03",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_05",
        area: "gossamer_gardens",
        title: "gg_05",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "",
        east: "",
        south: "gg_04",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_06",
        area: "gossamer_gardens",
        title: "gg_06",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "gg_03",
        east: "gg_22",
        south: "gg_07",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_07",
        area: "gossamer_gardens",
        title: "gg_07",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: ["grub_02"],
        npcs: [""],
        north: "gg_06",
        west: "",
        east: "",
        south: "gg_08",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_08",
        area: "gossamer_gardens",
        title: "The Bramble Path",
        description: "The ancient pathways were overgrown and hard to discern which was was which.",
        narration: "",
        update: "",
        items: ["thorny_bramble"],
        monsters: ["grub_01","grub_02"],
        npcs: [""],
        north: "gg_07",
        west: "",
        east: "gg_11",
        south: "gg_09",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_09",
        area: "gossamer_gardens",
        title: "The Rose Wall",
        description: "A barrier of twisted briar and thorn, blooming in red and pink roses rose high as a city wall.\n\nA hole leads into the tangle where some large animal broke it's way through.",
        narration: "",
        update: "",
        items: ["green_herb_pickup"],
        monsters: [""],
        npcs: ["ryth"],
        north: "gg_08",
        west: "",
        east: "",
        south: "edge_garden",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_11",
        area: "gossamer_gardens",
        title: "gg_11",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "gg_08",
        east: "gg_12",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_12",
        area: "gossamer_gardens",
        title: "gg_12",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: ["grub_03"],
        npcs: [""],
        north: "",
        west: "gg_11",
        east: "gg_13",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_13",
        area: "gossamer_gardens",
        title: "gg_13",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_14",
        west: "gg_12",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_14",
        area: "gossamer_gardens",
        title: "gg_14",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_15",
        west: "",
        east: "gg_20",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_15",
        area: "gossamer_gardens",
        title: "gg_15",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_16",
        west: "",
        east: "",
        south: "gg_14",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_16",
        area: "gossamer_gardens",
        title: "gg_16",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_17",
        west: "gg_24",
        east: "",
        south: "gg_15",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_17",
        area: "gossamer_gardens",
        title: "gg_17",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_18",
        west: "",
        east: "",
        south: "gg_16",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_18",
        area: "gossamer_gardens",
        title: "gg_18",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_19",
        west: "",
        east: "",
        south: "gg_17",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_19",
        area: "gossamer_gardens",
        title: "gg_19",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "",
        east: "",
        south: "gg_18",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_20",
        area: "gossamer_gardens",
        title: "gg_20",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "gg_14",
        east: "gg_21",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_21",
        area: "gossamer_gardens",
        title: "gg_21",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "gg_20",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_22",
        area: "gossamer_gardens",
        title: "gg_22",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "gg_23",
        west: "gg_06",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_23",
        area: "gossamer_gardens",
        title: "gg_23",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: ["grub_05"],
        npcs: [""],
        north: "",
        west: "",
        east: "gg_24",
        south: "gg_22",
        up: "",
        down: ""        
    },
    {        
        keyword: "gg_24",
        area: "gossamer_gardens",
        title: "gg_24",
        description: "Description",
        narration: "",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "gg_23",
        east: "gg_16",
        south: "",
        up: "",
        down: ""        
    },





    //----------------------//
    //-- ARCHIVE
    //----------------------//
   
    {
        area: "",
        keyword: "city_outskirts",
        title: "City Outskirts",
        description: "An old cobbled road leads you in among the ruined settlement. The buildings here are nothing more than cadaverous moss-covered remains.",
        narration: "outskirts",
        update: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "edge_woods",
        east: "crossroads",
        south: "",
        up: "",
        down: ""
    },        
    {
        area: "",
        keyword: "crossroads",
        title: "The Crossroads",        
        description: "All roads in this great city once came together here. Pathways spread forth from here to all corners of the ruins.",
        narration: "city_enter",
        items: ["green_herb_pickup"],
        monsters: [""],
        npcs: [""],
        north: "kings_road",
        west: "city_outskirts",
        east: "lake_shore",
        south: "temple_market",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "temple_market",
        title: "The Temple Market",        
        description: "A winding street, that once lead to a place of worship. The stones here are covered in rich green and purple mosses.\n\nPropped up inside a ruined wall is a makeshift tent, providing some respite from the dripping rain. From within, a small campfire is flickering away.",
        narration: "",
        update: "A soft rain sifts through the gray clouds above.",
        items: [""],
        monsters: [""],
        npcs: ["descendent","messenger"],
        north: "crossroads",
        west: "",
        east: "",
        south: "templefront",
        up: "",
        down: ""
    },    
    {
        area: "",
        keyword: "templefront",
        title: "The Templefront",        
        description: "A great temple stands before, it's walls have stood the test of time much better than most of this place.\n\nIt's made of a white stone that gleams under the moistness in the air.",
        narration: "",
        update: "Standing imposingly to the south is an ancient stone golem. It's head turns to face you.",
        items: ["green_herb_pickup"],
        monsters: ["temple_golem"],
        npcs: [""],
        north: "temple_market",
        west: "",
        east: "",
        south: "temple_arcades",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "temple_arcades",
        title: "The Temple Arcades",        
        description: "TO DO",
        narration: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "templefront",
        west: "",
        east: "",
        south: "",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "kings_road",
        title: "The King's Road",        
        description: "What was once a wide causeway for traders heading to the Temple Market is now home to the fallen remains of the tall stone buildings that once lined it.",
        narration: "",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "kings_gate",
        west: "lamplit_ruin",
        east: "sheltered_nook",
        south: "",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "lamplit_ruin",
        title: "A Lamplit Ruin",
        description: "A damp, mucky interior lit by the glow of a gently swinging grease lamp.",
        narration: "",
        items: [""],
        monsters: [""],
        npcs: ["jorrid"],
        north: "",
        west: "",
        east: "kings_road",
        south: "",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "kings_gate",
        title: "King's Gate",        
        description: "A crumbling wall still stands holding the arch of the old King's Gate.",
        narration: "",
        items: ["green_herb_pickup"],
        monsters: [""],
        npcs: ["thornhood_kijil"],
        north: "gate_stairwell",
        west: "",
        east: "",
        south: "kings_road",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "gate_stairwell",
        title: "The Gate Stairwell",        
        description: "The interior of the King's Gate foritifications hold a collapsed stone staircase that once lead up into the battlements.",
        narration: "",
        items: [""],
        monsters: [""],
        npcs: ["thornhood_soja"],
        north: "",
        west: "",
        east: "",
        south: "kings_gate",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "sheltered_nook",
        title: "A Sheltered Nook",        
        description: "You managed to find a cranny amongst the ruins with four walls and some degree of shelter from the rain.",
        narration: "",
        items: ["green_herb_pickup"],
        monsters: ["large_rat"],
        npcs: [""],
        north: "",
        west: "kings_road",
        east: "",
        south: "",
        up: "",
        down: ""
    },
    {
        area: "",
        keyword: "lake_shore",
        title: "Shore of the Black Lake",        
        description: "The city ruins collapse away into the perfectly still waters of the Black Lake.\n\nPainted deep in the water's depths is a vision of the castle. It calls to you.",
        narration: "approach_lake",
        items: [""],
        monsters: [""],
        npcs: [""],
        north: "",
        west: "crossroads",
        east: "",
        south: "",
        up: "",
        down: ""
    }

];
