
locations = [
    //----------------------//
    //-- The Old Monastery 
    //----------------------//
    {
        keyword: "east_gate",
        title: "The East Gate",        
        description: "A wide arched passage stood between two crumbling pieces of wall. It offered the Monastery little in terms of protection but the worn footpath leading outwards showed it still marked the border between the interior and the Valley beyond.",
        narration: "arrive_monastery",        
        update: "",        
        items: [],
        monsters: [],
        npcs: ["ryth"],
        north: "",
        west: "shrouded_plaza",
        east: "",
        south: "",
        up: "",
        down: ""        
    },
    {
        keyword: "shrouded_plaza",
        title: "The Shrouded Plaza",
        description: "A field of grass and flowers sat at the feet of an ancient looking Monastery. Tall grass and leaves overhead formed a tight canopy, giving this place a feeling of comfort and protection.",
        narration: "",        
        update: "",        
        items: [],
        monsters: [],
        npcs: ["plaza_camp"],
        north: "sanctum_steps",
        west: "western_gardens",
        east: "east_gate",
        south: "library",
        up: "",
        down: ""        
    },
    {
        keyword: "sanctum_steps",
        title: "The Sanctum Steps",
        description: "The steps leading up toward the Monastery Sanctum meandered back and forth making the trip up to the ancient building unneccsarily long.\n\nSmooth stone appeared in patches among the clinging moss and lichen that covered it.",
        narration: "",        
        update: "",        
        items: [],
        monsters: [],
        npcs: [],
        north: "sanctum_hall",
        west: "",
        east: "",
        south: "shrouded_plaza",
        up: "",
        down: "western_gardens"        
    },
    {
        keyword: "sanctum_hall",
        title: "The Sanctum Hall",
        description: "Shafts of light shone through old glass windows, illuminating a cavernous space inside the Monastery Sanctum.",
        narration: "",        
        update: "",        
        items: [],
        monsters: [],
        npcs: [],
        north: "sanctum_altar",
        west: "",
        east: "",
        south: "sanctum_steps",
        up: "",
        down: "kitchen"        
    },
    {
        keyword: "sanctum_altar",
        title: "The Sanctum Altar",
        description: "At the back of the Sanctum Hall was a low altar covered with ceramic dishes containing various offerings.\n\nDraped in shadow and standing watch over the altar was a large guardian-dog statue.\n\nIt's eyes were fierce and you swore you could see a flicker of flame within them.",
        narration: "",        
        update: "",        
        items: [],
        monsters: [],
        npcs: [],
        north: "",
        west: "",
        east: "",
        south: "sanctum_hall",
        up: "",
        down: ""        
    },
    {
        keyword: "kitchen",
        title: "Kitchen in the Cellars",
        description: "A series of low vaulted chambers meant to hold countless stocks of food and preserves, though they had been emptied long ago and never re-stocked.\n\nA warm light illuminated the chambers where a make shift kitchen had been constructed.",
        narration: "cellar",        
        update: "The smell of spices caught your nose and drew you to a dark stairway.",        
        items: [],
        monsters: [],
        npcs: ["oryan"],
        north: "",
        west: "",
        east: "",
        south: "",
        up: "sanctum_hall",
        down: ""        
    },
    {
        keyword: "library",
        title: "The Forest Library",
        description: "Once a place of gathered knowledge, it had long since been left to the earth, the floor sunken away to grass and soil, vines crawled up the clay walls.\n\nAt the back of the chamber, a staircase spiraled it's way upwards",
        narration: "library",        
        update: "",        
        items: [],
        monsters: [],
        npcs: [],
        north: "shrouded_plaza",
        west: "",
        east: "",
        south: "",
        up: "workshop",
        down: ""        
    },
    {
        keyword: "workshop",
        title: "The Tower Workshop",
        description: "A circular room at the uppermost floor of the Library with windows overlooking the surrounding Monastery grounds.\n\nA collection of work benches and strange contraptions sat in the middle of the room looking somewhat out of place.",
        narration: "workshop",        
        update: "",        
        items: [],
        monsters: [],
        npcs: [],
        north: "",
        west: "",
        east: "",
        south: "",
        up: "",
        down: "library"        
    },
    {
        keyword: "western_gardens",
        title: "The Western Gardens",
        description: "Hints of a magnificient garden in some age past can be seen in the manicured lines of stone paths. Now though the whole area has grown into a tangle of briar patches and reaching rose bushes.\n\nFinding your way through the maze of overgrowth is a challenge as many of the paths have become impassable.",
        narration: "western_gardens",        
        update: "",        
        items: ["thorny_bramble"],
        monsters: [],
        npcs: ["morgan"],
        north: "",
        west: "",
        east: "shrouded_plaza",
        south: "",
        up: "sanctum_steps",
        down: ""        
    },
    



    {
        keyword: "edge_wood",
        title: "Edge of the Woods",        
        description: "The darkened woods have slowly given way to shrubs and saplings where the forest meets the fields. A well-worn trail leads downhill to the ruins of an ancient city.",
        narration: "beginning",        
        update: "You awaken as if from a stupor. The last weeks blur together in your mind and where they've lead you is not entirely clear.",        
        items: ["green_herb_pickup"],
        monsters: [],
        npcs: ["plaza_camp"],
        north: "",
        west: "",
        east: "city_outskirts",
        south: "",
        up: "",
        down: ""        
    },
    {
        keyword: "city_outskirts",
        title: "City Outskirts",
        description: "An old cobbled road leads you in among the ruined settlement. The buildings here are nothing more than cadaverous moss-covered remains.",
        narration: "outskirts",
        update: "",
        items: [],
        monsters: [],
        npcs: [],
        north: "",
        west: "edge_wood",
        east: "crossroads",
        south: "",
        up: "",
        down: ""
    },        
    {
        keyword: "crossroads",
        title: "The Crossroads",        
        description: "All roads in this great city once came together here. Pathways spread forth from here to all corners of the ruins.",
        narration: "city_enter",
        items: ["green_herb_pickup"],
        monsters: [],
        npcs: [],
        north: "kings_road",
        west: "city_outskirts",
        east: "lake_shore",
        south: "temple_market",
        up: "",
        down: ""
    },
    {
        keyword: "temple_market",
        title: "The Temple Market",        
        description: "A winding street, that once lead to a place of worship. The stones here are covered in rich green and purple mosses.\n\nPropped up inside a ruined wall is a makeshift tent, providing some respite from the dripping rain. From within, a small campfire is flickering away.",
        narration: "",
        update: "A soft rain sifts through the gray clouds above.",
        items: [],
        monsters: [],
        npcs: ["descendent","messenger"],
        north: "crossroads",
        west: "",
        east: "",
        south: "templefront",
        up: "",
        down: ""
    },    
    {
        keyword: "templefront",
        title: "The Templefront",        
        description: "A great temple stands before, it's walls have stood the test of time much better than most of this place.\n\nIt's made of a white stone that gleams under the moistness in the air.",
        narration: "",
        update: "Standing imposingly to the south is an ancient stone golem. It's head turns to face you.",
        items: ["green_herb_pickup"],
        monsters: ["temple_golem"],
        npcs: [],
        north: "temple_market",
        west: "",
        east: "",
        south: "temple_arcades",
        up: "",
        down: ""
    },
    {
        keyword: "temple_arcades",
        title: "The Temple Arcades",        
        description: "TO DO",
        narration: "",
        items: [],
        monsters: [],
        npcs: [],
        north: "templefront",
        west: "",
        east: "",
        south: "",
        up: "",
        down: ""
    },
    {
        keyword: "kings_road",
        title: "The King's Road",        
        description: "What was once a wide causeway for traders heading to the Temple Market is now home to the fallen remains of the tall stone buildings that once lined it.",
        narration: "",
        items: [],
        monsters: [],
        npcs: [],
        north: "kings_gate",
        west: "lamplit_ruin",
        east: "sheltered_nook",
        south: "",
        up: "",
        down: ""
    },
    {
        keyword: "lamplit_ruin",
        title: "A Lamplit Ruin",
        description: "A damp, mucky interior lit by the glow of a gently swinging grease lamp.",
        narration: "",
        items: [],
        monsters: [],
        npcs: ["jorrid"],
        north: "",
        west: "",
        east: "kings_road",
        south: "",
        up: "",
        down: ""
    },
    {
        keyword: "kings_gate",
        title: "King's Gate",        
        description: "A crumbling wall still stands holding the arch of the old King's Gate.",
        narration: "",
        items: ["green_herb_pickup"],
        monsters: [],
        npcs: ["thornhood_kijil"],
        north: "gate_stairwell",
        west: "",
        east: "",
        south: "kings_road",
        up: "",
        down: ""
    },
    {
        keyword: "gate_stairwell",
        title: "The Gate Stairwell",        
        description: "The interior of the King's Gate foritifications hold a collapsed stone staircase that once lead up into the battlements.",
        narration: "",
        items: [],
        monsters: [],
        npcs: ["thornhood_soja"],
        north: "",
        west: "",
        east: "",
        south: "kings_gate",
        up: "",
        down: ""
    },
    {
        keyword: "sheltered_nook",
        title: "A Sheltered Nook",        
        description: "You managed to find a cranny amongst the ruins with four walls and some degree of shelter from the rain.",
        narration: "",
        items: ["green_herb_pickup"],
        monsters: ["large_rat"],
        npcs: [],
        north: "",
        west: "kings_road",
        east: "",
        south: "",
        up: "",
        down: ""
    },
    {
        keyword: "lake_shore",
        title: "Shore of the Black Lake",        
        description: "The city ruins collapse away into the perfectly still waters of the Black Lake.\n\nPainted deep in the water's depths is a vision of the castle. It calls to you.",
        narration: "approach_lake",
        items: [],
        monsters: [],
        npcs: [],
        north: "",
        west: "crossroads",
        east: "",
        south: "",
        up: "",
        down: ""
    }

];
